# Generated by Django 6.0.2 on 2026-02-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_alter_topic_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
