# Generated by Django 6.0.2 on 2026-02-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_rename_owner_id_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.AddField(
            model_name='topic',
            name='owner_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
