# Generated by Django 6.0.2 on 2026-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement_app', '0003_tasks_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='owner',
        ),
        migrations.AddField(
            model_name='tasks',
            name='owner_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
